// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analyzer.proto

package pulumirpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _struct "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// EnforcementLevel indicates the severity of a policy violation.
type EnforcementLevel int32

const (
	EnforcementLevel_ADVISORY  EnforcementLevel = 0
	EnforcementLevel_MANDATORY EnforcementLevel = 1
)

var EnforcementLevel_name = map[int32]string{
	0: "ADVISORY",
	1: "MANDATORY",
}
var EnforcementLevel_value = map[string]int32{
	"ADVISORY":  0,
	"MANDATORY": 1,
}

func (x EnforcementLevel) String() string {
	return proto.EnumName(EnforcementLevel_name, int32(x))
}
func (EnforcementLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{0}
}

type AnalyzeRequest struct {
	Type                 string                    `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Properties           *_struct.Struct           `protobuf:"bytes,2,opt,name=properties" json:"properties,omitempty"`
	Urn                  string                    `protobuf:"bytes,3,opt,name=urn" json:"urn,omitempty"`
	Name                 string                    `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Options              *AnalyzerResourceOptions  `protobuf:"bytes,5,opt,name=options" json:"options,omitempty"`
	Provider             *AnalyzerProviderResource `protobuf:"bytes,6,opt,name=provider" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *AnalyzeRequest) Reset()         { *m = AnalyzeRequest{} }
func (m *AnalyzeRequest) String() string { return proto.CompactTextString(m) }
func (*AnalyzeRequest) ProtoMessage()    {}
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{0}
}
func (m *AnalyzeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeRequest.Unmarshal(m, b)
}
func (m *AnalyzeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeRequest.Marshal(b, m, deterministic)
}
func (dst *AnalyzeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeRequest.Merge(dst, src)
}
func (m *AnalyzeRequest) XXX_Size() int {
	return xxx_messageInfo_AnalyzeRequest.Size(m)
}
func (m *AnalyzeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeRequest proto.InternalMessageInfo

func (m *AnalyzeRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AnalyzeRequest) GetProperties() *_struct.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *AnalyzeRequest) GetUrn() string {
	if m != nil {
		return m.Urn
	}
	return ""
}

func (m *AnalyzeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnalyzeRequest) GetOptions() *AnalyzerResourceOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *AnalyzeRequest) GetProvider() *AnalyzerProviderResource {
	if m != nil {
		return m.Provider
	}
	return nil
}

// AnalyzerResource defines the view of a Pulumi-managed resource as sent to Analyzers. The properties
// of the resource are specific to the type of analysis being performed. See the Analyzer
// service definition for more information.
type AnalyzerResource struct {
	Type                 string                                   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Properties           *_struct.Struct                          `protobuf:"bytes,2,opt,name=properties" json:"properties,omitempty"`
	Urn                  string                                   `protobuf:"bytes,3,opt,name=urn" json:"urn,omitempty"`
	Name                 string                                   `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Options              *AnalyzerResourceOptions                 `protobuf:"bytes,5,opt,name=options" json:"options,omitempty"`
	Provider             *AnalyzerProviderResource                `protobuf:"bytes,6,opt,name=provider" json:"provider,omitempty"`
	Parent               string                                   `protobuf:"bytes,7,opt,name=parent" json:"parent,omitempty"`
	Dependencies         []string                                 `protobuf:"bytes,8,rep,name=dependencies" json:"dependencies,omitempty"`
	PropertyDependencies map[string]*AnalyzerPropertyDependencies `protobuf:"bytes,9,rep,name=propertyDependencies" json:"propertyDependencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *AnalyzerResource) Reset()         { *m = AnalyzerResource{} }
func (m *AnalyzerResource) String() string { return proto.CompactTextString(m) }
func (*AnalyzerResource) ProtoMessage()    {}
func (*AnalyzerResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{1}
}
func (m *AnalyzerResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzerResource.Unmarshal(m, b)
}
func (m *AnalyzerResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzerResource.Marshal(b, m, deterministic)
}
func (dst *AnalyzerResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzerResource.Merge(dst, src)
}
func (m *AnalyzerResource) XXX_Size() int {
	return xxx_messageInfo_AnalyzerResource.Size(m)
}
func (m *AnalyzerResource) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzerResource.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzerResource proto.InternalMessageInfo

func (m *AnalyzerResource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AnalyzerResource) GetProperties() *_struct.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *AnalyzerResource) GetUrn() string {
	if m != nil {
		return m.Urn
	}
	return ""
}

func (m *AnalyzerResource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnalyzerResource) GetOptions() *AnalyzerResourceOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *AnalyzerResource) GetProvider() *AnalyzerProviderResource {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *AnalyzerResource) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *AnalyzerResource) GetDependencies() []string {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *AnalyzerResource) GetPropertyDependencies() map[string]*AnalyzerPropertyDependencies {
	if m != nil {
		return m.PropertyDependencies
	}
	return nil
}

// AnalyzerResourceOptions defines the options associated with a resource.
type AnalyzerResourceOptions struct {
	Protect                    bool                                    `protobuf:"varint,1,opt,name=protect" json:"protect,omitempty"`
	IgnoreChanges              []string                                `protobuf:"bytes,2,rep,name=ignoreChanges" json:"ignoreChanges,omitempty"`
	DeleteBeforeReplace        bool                                    `protobuf:"varint,3,opt,name=deleteBeforeReplace" json:"deleteBeforeReplace,omitempty"`
	DeleteBeforeReplaceDefined bool                                    `protobuf:"varint,4,opt,name=deleteBeforeReplaceDefined" json:"deleteBeforeReplaceDefined,omitempty"`
	AdditionalSecretOutputs    []string                                `protobuf:"bytes,5,rep,name=additionalSecretOutputs" json:"additionalSecretOutputs,omitempty"`
	Aliases                    []string                                `protobuf:"bytes,6,rep,name=aliases" json:"aliases,omitempty"`
	CustomTimeouts             *AnalyzerResourceOptions_CustomTimeouts `protobuf:"bytes,7,opt,name=customTimeouts" json:"customTimeouts,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                                `json:"-"`
	XXX_unrecognized           []byte                                  `json:"-"`
	XXX_sizecache              int32                                   `json:"-"`
}

func (m *AnalyzerResourceOptions) Reset()         { *m = AnalyzerResourceOptions{} }
func (m *AnalyzerResourceOptions) String() string { return proto.CompactTextString(m) }
func (*AnalyzerResourceOptions) ProtoMessage()    {}
func (*AnalyzerResourceOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{2}
}
func (m *AnalyzerResourceOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzerResourceOptions.Unmarshal(m, b)
}
func (m *AnalyzerResourceOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzerResourceOptions.Marshal(b, m, deterministic)
}
func (dst *AnalyzerResourceOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzerResourceOptions.Merge(dst, src)
}
func (m *AnalyzerResourceOptions) XXX_Size() int {
	return xxx_messageInfo_AnalyzerResourceOptions.Size(m)
}
func (m *AnalyzerResourceOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzerResourceOptions.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzerResourceOptions proto.InternalMessageInfo

func (m *AnalyzerResourceOptions) GetProtect() bool {
	if m != nil {
		return m.Protect
	}
	return false
}

func (m *AnalyzerResourceOptions) GetIgnoreChanges() []string {
	if m != nil {
		return m.IgnoreChanges
	}
	return nil
}

func (m *AnalyzerResourceOptions) GetDeleteBeforeReplace() bool {
	if m != nil {
		return m.DeleteBeforeReplace
	}
	return false
}

func (m *AnalyzerResourceOptions) GetDeleteBeforeReplaceDefined() bool {
	if m != nil {
		return m.DeleteBeforeReplaceDefined
	}
	return false
}

func (m *AnalyzerResourceOptions) GetAdditionalSecretOutputs() []string {
	if m != nil {
		return m.AdditionalSecretOutputs
	}
	return nil
}

func (m *AnalyzerResourceOptions) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

func (m *AnalyzerResourceOptions) GetCustomTimeouts() *AnalyzerResourceOptions_CustomTimeouts {
	if m != nil {
		return m.CustomTimeouts
	}
	return nil
}

// CustomTimeouts allows a user to be able to create a set of custom timeout parameters.
type AnalyzerResourceOptions_CustomTimeouts struct {
	Create               float64  `protobuf:"fixed64,1,opt,name=create" json:"create,omitempty"`
	Update               float64  `protobuf:"fixed64,2,opt,name=update" json:"update,omitempty"`
	Delete               float64  `protobuf:"fixed64,3,opt,name=delete" json:"delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnalyzerResourceOptions_CustomTimeouts) Reset() {
	*m = AnalyzerResourceOptions_CustomTimeouts{}
}
func (m *AnalyzerResourceOptions_CustomTimeouts) String() string { return proto.CompactTextString(m) }
func (*AnalyzerResourceOptions_CustomTimeouts) ProtoMessage()    {}
func (*AnalyzerResourceOptions_CustomTimeouts) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{2, 0}
}
func (m *AnalyzerResourceOptions_CustomTimeouts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzerResourceOptions_CustomTimeouts.Unmarshal(m, b)
}
func (m *AnalyzerResourceOptions_CustomTimeouts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzerResourceOptions_CustomTimeouts.Marshal(b, m, deterministic)
}
func (dst *AnalyzerResourceOptions_CustomTimeouts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzerResourceOptions_CustomTimeouts.Merge(dst, src)
}
func (m *AnalyzerResourceOptions_CustomTimeouts) XXX_Size() int {
	return xxx_messageInfo_AnalyzerResourceOptions_CustomTimeouts.Size(m)
}
func (m *AnalyzerResourceOptions_CustomTimeouts) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzerResourceOptions_CustomTimeouts.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzerResourceOptions_CustomTimeouts proto.InternalMessageInfo

func (m *AnalyzerResourceOptions_CustomTimeouts) GetCreate() float64 {
	if m != nil {
		return m.Create
	}
	return 0
}

func (m *AnalyzerResourceOptions_CustomTimeouts) GetUpdate() float64 {
	if m != nil {
		return m.Update
	}
	return 0
}

func (m *AnalyzerResourceOptions_CustomTimeouts) GetDelete() float64 {
	if m != nil {
		return m.Delete
	}
	return 0
}

// AnalyzerProviderResource provides information about a resource's provider.
type AnalyzerProviderResource struct {
	Type                 string          `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Properties           *_struct.Struct `protobuf:"bytes,2,opt,name=properties" json:"properties,omitempty"`
	Urn                  string          `protobuf:"bytes,3,opt,name=urn" json:"urn,omitempty"`
	Name                 string          `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AnalyzerProviderResource) Reset()         { *m = AnalyzerProviderResource{} }
func (m *AnalyzerProviderResource) String() string { return proto.CompactTextString(m) }
func (*AnalyzerProviderResource) ProtoMessage()    {}
func (*AnalyzerProviderResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{3}
}
func (m *AnalyzerProviderResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzerProviderResource.Unmarshal(m, b)
}
func (m *AnalyzerProviderResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzerProviderResource.Marshal(b, m, deterministic)
}
func (dst *AnalyzerProviderResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzerProviderResource.Merge(dst, src)
}
func (m *AnalyzerProviderResource) XXX_Size() int {
	return xxx_messageInfo_AnalyzerProviderResource.Size(m)
}
func (m *AnalyzerProviderResource) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzerProviderResource.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzerProviderResource proto.InternalMessageInfo

func (m *AnalyzerProviderResource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AnalyzerProviderResource) GetProperties() *_struct.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *AnalyzerProviderResource) GetUrn() string {
	if m != nil {
		return m.Urn
	}
	return ""
}

func (m *AnalyzerProviderResource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// AnalyzerPropertyDependencies describes the resources that a particular property depends on.
type AnalyzerPropertyDependencies struct {
	Urns                 []string `protobuf:"bytes,1,rep,name=urns" json:"urns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnalyzerPropertyDependencies) Reset()         { *m = AnalyzerPropertyDependencies{} }
func (m *AnalyzerPropertyDependencies) String() string { return proto.CompactTextString(m) }
func (*AnalyzerPropertyDependencies) ProtoMessage()    {}
func (*AnalyzerPropertyDependencies) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{4}
}
func (m *AnalyzerPropertyDependencies) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzerPropertyDependencies.Unmarshal(m, b)
}
func (m *AnalyzerPropertyDependencies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzerPropertyDependencies.Marshal(b, m, deterministic)
}
func (dst *AnalyzerPropertyDependencies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzerPropertyDependencies.Merge(dst, src)
}
func (m *AnalyzerPropertyDependencies) XXX_Size() int {
	return xxx_messageInfo_AnalyzerPropertyDependencies.Size(m)
}
func (m *AnalyzerPropertyDependencies) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzerPropertyDependencies.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzerPropertyDependencies proto.InternalMessageInfo

func (m *AnalyzerPropertyDependencies) GetUrns() []string {
	if m != nil {
		return m.Urns
	}
	return nil
}

type AnalyzeStackRequest struct {
	Resources            []*AnalyzerResource `protobuf:"bytes,1,rep,name=resources" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AnalyzeStackRequest) Reset()         { *m = AnalyzeStackRequest{} }
func (m *AnalyzeStackRequest) String() string { return proto.CompactTextString(m) }
func (*AnalyzeStackRequest) ProtoMessage()    {}
func (*AnalyzeStackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{5}
}
func (m *AnalyzeStackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeStackRequest.Unmarshal(m, b)
}
func (m *AnalyzeStackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeStackRequest.Marshal(b, m, deterministic)
}
func (dst *AnalyzeStackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeStackRequest.Merge(dst, src)
}
func (m *AnalyzeStackRequest) XXX_Size() int {
	return xxx_messageInfo_AnalyzeStackRequest.Size(m)
}
func (m *AnalyzeStackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeStackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeStackRequest proto.InternalMessageInfo

func (m *AnalyzeStackRequest) GetResources() []*AnalyzerResource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type AnalyzeResponse struct {
	Diagnostics          []*AnalyzeDiagnostic `protobuf:"bytes,2,rep,name=diagnostics" json:"diagnostics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AnalyzeResponse) Reset()         { *m = AnalyzeResponse{} }
func (m *AnalyzeResponse) String() string { return proto.CompactTextString(m) }
func (*AnalyzeResponse) ProtoMessage()    {}
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{6}
}
func (m *AnalyzeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeResponse.Unmarshal(m, b)
}
func (m *AnalyzeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeResponse.Marshal(b, m, deterministic)
}
func (dst *AnalyzeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeResponse.Merge(dst, src)
}
func (m *AnalyzeResponse) XXX_Size() int {
	return xxx_messageInfo_AnalyzeResponse.Size(m)
}
func (m *AnalyzeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeResponse proto.InternalMessageInfo

func (m *AnalyzeResponse) GetDiagnostics() []*AnalyzeDiagnostic {
	if m != nil {
		return m.Diagnostics
	}
	return nil
}

type AnalyzeDiagnostic struct {
	PolicyName           string           `protobuf:"bytes,1,opt,name=policyName" json:"policyName,omitempty"`
	PolicyPackName       string           `protobuf:"bytes,2,opt,name=policyPackName" json:"policyPackName,omitempty"`
	PolicyPackVersion    string           `protobuf:"bytes,3,opt,name=policyPackVersion" json:"policyPackVersion,omitempty"`
	Description          string           `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Message              string           `protobuf:"bytes,5,opt,name=message" json:"message,omitempty"`
	Tags                 []string         `protobuf:"bytes,6,rep,name=tags" json:"tags,omitempty"`
	EnforcementLevel     EnforcementLevel `protobuf:"varint,7,opt,name=enforcementLevel,enum=pulumirpc.EnforcementLevel" json:"enforcementLevel,omitempty"`
	Urn                  string           `protobuf:"bytes,8,opt,name=urn" json:"urn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AnalyzeDiagnostic) Reset()         { *m = AnalyzeDiagnostic{} }
func (m *AnalyzeDiagnostic) String() string { return proto.CompactTextString(m) }
func (*AnalyzeDiagnostic) ProtoMessage()    {}
func (*AnalyzeDiagnostic) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{7}
}
func (m *AnalyzeDiagnostic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeDiagnostic.Unmarshal(m, b)
}
func (m *AnalyzeDiagnostic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeDiagnostic.Marshal(b, m, deterministic)
}
func (dst *AnalyzeDiagnostic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeDiagnostic.Merge(dst, src)
}
func (m *AnalyzeDiagnostic) XXX_Size() int {
	return xxx_messageInfo_AnalyzeDiagnostic.Size(m)
}
func (m *AnalyzeDiagnostic) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeDiagnostic.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeDiagnostic proto.InternalMessageInfo

func (m *AnalyzeDiagnostic) GetPolicyName() string {
	if m != nil {
		return m.PolicyName
	}
	return ""
}

func (m *AnalyzeDiagnostic) GetPolicyPackName() string {
	if m != nil {
		return m.PolicyPackName
	}
	return ""
}

func (m *AnalyzeDiagnostic) GetPolicyPackVersion() string {
	if m != nil {
		return m.PolicyPackVersion
	}
	return ""
}

func (m *AnalyzeDiagnostic) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AnalyzeDiagnostic) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AnalyzeDiagnostic) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *AnalyzeDiagnostic) GetEnforcementLevel() EnforcementLevel {
	if m != nil {
		return m.EnforcementLevel
	}
	return EnforcementLevel_ADVISORY
}

func (m *AnalyzeDiagnostic) GetUrn() string {
	if m != nil {
		return m.Urn
	}
	return ""
}

// AnalyzerInfo provides metadata about a PolicyPack inside an analyzer.
type AnalyzerInfo struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DisplayName          string        `protobuf:"bytes,2,opt,name=displayName" json:"displayName,omitempty"`
	Policies             []*PolicyInfo `protobuf:"bytes,3,rep,name=policies" json:"policies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AnalyzerInfo) Reset()         { *m = AnalyzerInfo{} }
func (m *AnalyzerInfo) String() string { return proto.CompactTextString(m) }
func (*AnalyzerInfo) ProtoMessage()    {}
func (*AnalyzerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{8}
}
func (m *AnalyzerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzerInfo.Unmarshal(m, b)
}
func (m *AnalyzerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzerInfo.Marshal(b, m, deterministic)
}
func (dst *AnalyzerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzerInfo.Merge(dst, src)
}
func (m *AnalyzerInfo) XXX_Size() int {
	return xxx_messageInfo_AnalyzerInfo.Size(m)
}
func (m *AnalyzerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzerInfo proto.InternalMessageInfo

func (m *AnalyzerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnalyzerInfo) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *AnalyzerInfo) GetPolicies() []*PolicyInfo {
	if m != nil {
		return m.Policies
	}
	return nil
}

// PolicyInfo provides metadata about an individual Policy within a Policy Pack.
type PolicyInfo struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DisplayName          string                 `protobuf:"bytes,2,opt,name=displayName" json:"displayName,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	EnforcementLevel     EnforcementLevel       `protobuf:"varint,5,opt,name=enforcementLevel,enum=pulumirpc.EnforcementLevel" json:"enforcementLevel,omitempty"`
	Config               *PolicyInfo_ConfigInfo `protobuf:"bytes,6,opt,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PolicyInfo) Reset()         { *m = PolicyInfo{} }
func (m *PolicyInfo) String() string { return proto.CompactTextString(m) }
func (*PolicyInfo) ProtoMessage()    {}
func (*PolicyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{9}
}
func (m *PolicyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyInfo.Unmarshal(m, b)
}
func (m *PolicyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyInfo.Marshal(b, m, deterministic)
}
func (dst *PolicyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyInfo.Merge(dst, src)
}
func (m *PolicyInfo) XXX_Size() int {
	return xxx_messageInfo_PolicyInfo.Size(m)
}
func (m *PolicyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyInfo proto.InternalMessageInfo

func (m *PolicyInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PolicyInfo) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *PolicyInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PolicyInfo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PolicyInfo) GetEnforcementLevel() EnforcementLevel {
	if m != nil {
		return m.EnforcementLevel
	}
	return EnforcementLevel_ADVISORY
}

func (m *PolicyInfo) GetConfig() *PolicyInfo_ConfigInfo {
	if m != nil {
		return m.Config
	}
	return nil
}

// ConfigInfo provides metadata about a Policy's config.
type PolicyInfo_ConfigInfo struct {
	Properties           *_struct.Struct `protobuf:"bytes,1,opt,name=properties" json:"properties,omitempty"`
	Required             []string        `protobuf:"bytes,2,rep,name=required" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PolicyInfo_ConfigInfo) Reset()         { *m = PolicyInfo_ConfigInfo{} }
func (m *PolicyInfo_ConfigInfo) String() string { return proto.CompactTextString(m) }
func (*PolicyInfo_ConfigInfo) ProtoMessage()    {}
func (*PolicyInfo_ConfigInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{9, 0}
}
func (m *PolicyInfo_ConfigInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyInfo_ConfigInfo.Unmarshal(m, b)
}
func (m *PolicyInfo_ConfigInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyInfo_ConfigInfo.Marshal(b, m, deterministic)
}
func (dst *PolicyInfo_ConfigInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyInfo_ConfigInfo.Merge(dst, src)
}
func (m *PolicyInfo_ConfigInfo) XXX_Size() int {
	return xxx_messageInfo_PolicyInfo_ConfigInfo.Size(m)
}
func (m *PolicyInfo_ConfigInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyInfo_ConfigInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyInfo_ConfigInfo proto.InternalMessageInfo

func (m *PolicyInfo_ConfigInfo) GetProperties() *_struct.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *PolicyInfo_ConfigInfo) GetRequired() []string {
	if m != nil {
		return m.Required
	}
	return nil
}

// ConfigureAnalyzerRequest provides configuration information to the analyzer.
type ConfigureAnalyzerRequest struct {
	PolicyConfig         map[string]*ConfigureAnalyzerRequest_PolicyConfig `protobuf:"bytes,1,rep,name=policyConfig" json:"policyConfig,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                                          `json:"-"`
	XXX_unrecognized     []byte                                            `json:"-"`
	XXX_sizecache        int32                                             `json:"-"`
}

func (m *ConfigureAnalyzerRequest) Reset()         { *m = ConfigureAnalyzerRequest{} }
func (m *ConfigureAnalyzerRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigureAnalyzerRequest) ProtoMessage()    {}
func (*ConfigureAnalyzerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{10}
}
func (m *ConfigureAnalyzerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureAnalyzerRequest.Unmarshal(m, b)
}
func (m *ConfigureAnalyzerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureAnalyzerRequest.Marshal(b, m, deterministic)
}
func (dst *ConfigureAnalyzerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureAnalyzerRequest.Merge(dst, src)
}
func (m *ConfigureAnalyzerRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigureAnalyzerRequest.Size(m)
}
func (m *ConfigureAnalyzerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureAnalyzerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureAnalyzerRequest proto.InternalMessageInfo

func (m *ConfigureAnalyzerRequest) GetPolicyConfig() map[string]*ConfigureAnalyzerRequest_PolicyConfig {
	if m != nil {
		return m.PolicyConfig
	}
	return nil
}

type ConfigureAnalyzerRequest_PolicyConfig struct {
	EnforcementLevel        EnforcementLevel `protobuf:"varint,1,opt,name=enforcementLevel,enum=pulumirpc.EnforcementLevel" json:"enforcementLevel,omitempty"`
	EnforcementLevelDefined bool             `protobuf:"varint,2,opt,name=enforcementLevelDefined" json:"enforcementLevelDefined,omitempty"`
	Properties              *_struct.Struct  `protobuf:"bytes,3,opt,name=properties" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}         `json:"-"`
	XXX_unrecognized        []byte           `json:"-"`
	XXX_sizecache           int32            `json:"-"`
}

func (m *ConfigureAnalyzerRequest_PolicyConfig) Reset()         { *m = ConfigureAnalyzerRequest_PolicyConfig{} }
func (m *ConfigureAnalyzerRequest_PolicyConfig) String() string { return proto.CompactTextString(m) }
func (*ConfigureAnalyzerRequest_PolicyConfig) ProtoMessage()    {}
func (*ConfigureAnalyzerRequest_PolicyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyzer_6d3098ca1368e84e, []int{10, 0}
}
func (m *ConfigureAnalyzerRequest_PolicyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureAnalyzerRequest_PolicyConfig.Unmarshal(m, b)
}
func (m *ConfigureAnalyzerRequest_PolicyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureAnalyzerRequest_PolicyConfig.Marshal(b, m, deterministic)
}
func (dst *ConfigureAnalyzerRequest_PolicyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureAnalyzerRequest_PolicyConfig.Merge(dst, src)
}
func (m *ConfigureAnalyzerRequest_PolicyConfig) XXX_Size() int {
	return xxx_messageInfo_ConfigureAnalyzerRequest_PolicyConfig.Size(m)
}
func (m *ConfigureAnalyzerRequest_PolicyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureAnalyzerRequest_PolicyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureAnalyzerRequest_PolicyConfig proto.InternalMessageInfo

func (m *ConfigureAnalyzerRequest_PolicyConfig) GetEnforcementLevel() EnforcementLevel {
	if m != nil {
		return m.EnforcementLevel
	}
	return EnforcementLevel_ADVISORY
}

func (m *ConfigureAnalyzerRequest_PolicyConfig) GetEnforcementLevelDefined() bool {
	if m != nil {
		return m.EnforcementLevelDefined
	}
	return false
}

func (m *ConfigureAnalyzerRequest_PolicyConfig) GetProperties() *_struct.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

func init() {
	proto.RegisterType((*AnalyzeRequest)(nil), "pulumirpc.AnalyzeRequest")
	proto.RegisterType((*AnalyzerResource)(nil), "pulumirpc.AnalyzerResource")
	proto.RegisterMapType((map[string]*AnalyzerPropertyDependencies)(nil), "pulumirpc.AnalyzerResource.PropertyDependenciesEntry")
	proto.RegisterType((*AnalyzerResourceOptions)(nil), "pulumirpc.AnalyzerResourceOptions")
	proto.RegisterType((*AnalyzerResourceOptions_CustomTimeouts)(nil), "pulumirpc.AnalyzerResourceOptions.CustomTimeouts")
	proto.RegisterType((*AnalyzerProviderResource)(nil), "pulumirpc.AnalyzerProviderResource")
	proto.RegisterType((*AnalyzerPropertyDependencies)(nil), "pulumirpc.AnalyzerPropertyDependencies")
	proto.RegisterType((*AnalyzeStackRequest)(nil), "pulumirpc.AnalyzeStackRequest")
	proto.RegisterType((*AnalyzeResponse)(nil), "pulumirpc.AnalyzeResponse")
	proto.RegisterType((*AnalyzeDiagnostic)(nil), "pulumirpc.AnalyzeDiagnostic")
	proto.RegisterType((*AnalyzerInfo)(nil), "pulumirpc.AnalyzerInfo")
	proto.RegisterType((*PolicyInfo)(nil), "pulumirpc.PolicyInfo")
	proto.RegisterType((*PolicyInfo_ConfigInfo)(nil), "pulumirpc.PolicyInfo.ConfigInfo")
	proto.RegisterType((*ConfigureAnalyzerRequest)(nil), "pulumirpc.ConfigureAnalyzerRequest")
	proto.RegisterMapType((map[string]*ConfigureAnalyzerRequest_PolicyConfig)(nil), "pulumirpc.ConfigureAnalyzerRequest.PolicyConfigEntry")
	proto.RegisterType((*ConfigureAnalyzerRequest_PolicyConfig)(nil), "pulumirpc.ConfigureAnalyzerRequest.PolicyConfig")
	proto.RegisterEnum("pulumirpc.EnforcementLevel", EnforcementLevel_name, EnforcementLevel_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Analyzer service

type AnalyzerClient interface {
	// Analyze analyzes a single resource object, and returns any errors that it finds.
	// Called with the "inputs" to the resource, before it is updated.
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	// AnalyzeStack analyzes all resources within a stack, at the end of a successful
	// preview or update. The provided resources are the "outputs", after any mutations
	// have taken place.
	AnalyzeStack(ctx context.Context, in *AnalyzeStackRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	// GetAnalyzerInfo returns metadata about the analyzer (e.g., list of policies contained).
	GetAnalyzerInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AnalyzerInfo, error)
	// GetPluginInfo returns generic information about this plugin, like its version.
	GetPluginInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	// Configure configures the analyzer, passing configuration properties for each policy.
	Configure(ctx context.Context, in *ConfigureAnalyzerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type analyzerClient struct {
	cc *grpc.ClientConn
}

func NewAnalyzerClient(cc *grpc.ClientConn) AnalyzerClient {
	return &analyzerClient{cc}
}

func (c *analyzerClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	out := new(AnalyzeResponse)
	err := grpc.Invoke(ctx, "/pulumirpc.Analyzer/Analyze", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerClient) AnalyzeStack(ctx context.Context, in *AnalyzeStackRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	out := new(AnalyzeResponse)
	err := grpc.Invoke(ctx, "/pulumirpc.Analyzer/AnalyzeStack", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerClient) GetAnalyzerInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AnalyzerInfo, error) {
	out := new(AnalyzerInfo)
	err := grpc.Invoke(ctx, "/pulumirpc.Analyzer/GetAnalyzerInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerClient) GetPluginInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	out := new(PluginInfo)
	err := grpc.Invoke(ctx, "/pulumirpc.Analyzer/GetPluginInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerClient) Configure(ctx context.Context, in *ConfigureAnalyzerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := grpc.Invoke(ctx, "/pulumirpc.Analyzer/Configure", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Analyzer service

type AnalyzerServer interface {
	// Analyze analyzes a single resource object, and returns any errors that it finds.
	// Called with the "inputs" to the resource, before it is updated.
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	// AnalyzeStack analyzes all resources within a stack, at the end of a successful
	// preview or update. The provided resources are the "outputs", after any mutations
	// have taken place.
	AnalyzeStack(context.Context, *AnalyzeStackRequest) (*AnalyzeResponse, error)
	// GetAnalyzerInfo returns metadata about the analyzer (e.g., list of policies contained).
	GetAnalyzerInfo(context.Context, *empty.Empty) (*AnalyzerInfo, error)
	// GetPluginInfo returns generic information about this plugin, like its version.
	GetPluginInfo(context.Context, *empty.Empty) (*PluginInfo, error)
	// Configure configures the analyzer, passing configuration properties for each policy.
	Configure(context.Context, *ConfigureAnalyzerRequest) (*empty.Empty, error)
}

func RegisterAnalyzerServer(s *grpc.Server, srv AnalyzerServer) {
	s.RegisterService(&_Analyzer_serviceDesc, srv)
}

func _Analyzer_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pulumirpc.Analyzer/Analyze",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analyzer_AnalyzeStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServer).AnalyzeStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pulumirpc.Analyzer/AnalyzeStack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServer).AnalyzeStack(ctx, req.(*AnalyzeStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analyzer_GetAnalyzerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServer).GetAnalyzerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pulumirpc.Analyzer/GetAnalyzerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServer).GetAnalyzerInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analyzer_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pulumirpc.Analyzer/GetPluginInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServer).GetPluginInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analyzer_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureAnalyzerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pulumirpc.Analyzer/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServer).Configure(ctx, req.(*ConfigureAnalyzerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Analyzer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pulumirpc.Analyzer",
	HandlerType: (*AnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _Analyzer_Analyze_Handler,
		},
		{
			MethodName: "AnalyzeStack",
			Handler:    _Analyzer_AnalyzeStack_Handler,
		},
		{
			MethodName: "GetAnalyzerInfo",
			Handler:    _Analyzer_GetAnalyzerInfo_Handler,
		},
		{
			MethodName: "GetPluginInfo",
			Handler:    _Analyzer_GetPluginInfo_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Analyzer_Configure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analyzer.proto",
}

func init() { proto.RegisterFile("analyzer.proto", fileDescriptor_analyzer_6d3098ca1368e84e) }

var fileDescriptor_analyzer_6d3098ca1368e84e = []byte{
	// 1072 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe4, 0x57, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x8e, 0xec, 0xfc, 0xd8, 0xc7, 0x8e, 0x9b, 0x6c, 0xa1, 0x51, 0xd5, 0x4c, 0xc7, 0xa3, 0x32,
	0x90, 0x61, 0x18, 0xa7, 0x35, 0xc3, 0x10, 0x18, 0xfe, 0xd2, 0x38, 0x64, 0xca, 0x94, 0xc6, 0x6c,
	0x3a, 0x1d, 0x72, 0xa9, 0x4a, 0xc7, 0x46, 0x13, 0x59, 0xab, 0xac, 0x56, 0x61, 0xcc, 0x25, 0xf7,
	0x3c, 0x02, 0x6f, 0x01, 0x2f, 0xc1, 0x35, 0x8f, 0xc0, 0x03, 0xf0, 0x08, 0xcc, 0xee, 0x4a, 0x8a,
	0x2c, 0xcb, 0x6e, 0xc8, 0x0d, 0x17, 0xdc, 0xed, 0x39, 0xe7, 0x3b, 0x67, 0xf7, 0x7c, 0xfb, 0xed,
	0xae, 0x04, 0x1d, 0x27, 0x74, 0x82, 0xe9, 0x4f, 0xc8, 0x7b, 0x11, 0x67, 0x82, 0x91, 0x66, 0x94,
	0x04, 0xc9, 0xc4, 0xe7, 0x91, 0x6b, 0xb5, 0xa3, 0x20, 0x19, 0xfb, 0xa1, 0x0e, 0x58, 0x0f, 0xc6,
	0x8c, 0x8d, 0x03, 0xdc, 0x57, 0xd6, 0xeb, 0x64, 0xb4, 0x8f, 0x93, 0x48, 0x4c, 0xd3, 0xe0, 0x6e,
	0x39, 0x18, 0x0b, 0x9e, 0xb8, 0x42, 0x47, 0xed, 0x9f, 0x6b, 0xd0, 0x39, 0xd4, 0xd3, 0x50, 0xbc,
	0x4c, 0x30, 0x16, 0x84, 0xc0, 0xaa, 0x98, 0x46, 0x68, 0x1a, 0x5d, 0x63, 0xaf, 0x49, 0xd5, 0x98,
	0x7c, 0x0c, 0x10, 0x71, 0x16, 0x21, 0x17, 0x3e, 0xc6, 0x66, 0xad, 0x6b, 0xec, 0xb5, 0xfa, 0x3b,
	0x3d, 0x5d, 0xb9, 0x97, 0x55, 0xee, 0x9d, 0xa9, 0xca, 0xb4, 0x00, 0x25, 0x5b, 0x50, 0x4f, 0x78,
	0x68, 0xd6, 0x55, 0x2d, 0x39, 0x94, 0xe5, 0x43, 0x67, 0x82, 0xe6, 0xaa, 0x2e, 0x2f, 0xc7, 0xe4,
	0x33, 0xd8, 0x60, 0x91, 0xf0, 0x59, 0x18, 0x9b, 0x6b, 0xaa, 0xb6, 0xdd, 0xcb, 0x7b, 0xed, 0xa5,
	0xcb, 0xe3, 0x14, 0x63, 0x96, 0x70, 0x17, 0x4f, 0x35, 0x92, 0x66, 0x29, 0xe4, 0x4b, 0x68, 0x44,
	0x9c, 0x5d, 0xf9, 0x1e, 0x72, 0x73, 0x5d, 0xa5, 0x3f, 0xaa, 0x48, 0x1f, 0xa6, 0x90, 0xac, 0x0c,
	0xcd, 0x93, 0xec, 0x5f, 0x57, 0x61, 0xab, 0x3c, 0xcb, 0xff, 0x8f, 0x06, 0x72, 0x0f, 0xd6, 0x23,
	0x87, 0x63, 0x28, 0xcc, 0x0d, 0xb5, 0xa8, 0xd4, 0x22, 0x36, 0xb4, 0x3d, 0x8c, 0x30, 0xf4, 0x30,
	0x74, 0x65, 0xdf, 0x8d, 0x6e, 0x7d, 0xaf, 0x49, 0x67, 0x7c, 0xc4, 0x87, 0xb7, 0xd2, 0x76, 0xa7,
	0x83, 0x22, 0xb6, 0xd9, 0xad, 0xef, 0xb5, 0xfa, 0x1f, 0x2d, 0xe9, 0xa3, 0x37, 0xac, 0xc8, 0x3b,
	0x0e, 0x05, 0x9f, 0xd2, 0xca, 0x92, 0x56, 0x04, 0xf7, 0x17, 0xa6, 0x48, 0xa2, 0x2f, 0x70, 0x9a,
	0x6e, 0x9a, 0x1c, 0x92, 0xcf, 0x61, 0xed, 0xca, 0x09, 0x12, 0x4c, 0xb7, 0xeb, 0xbd, 0x6a, 0x4e,
	0xe6, 0xca, 0x51, 0x9d, 0xf5, 0x69, 0xed, 0xc0, 0xb0, 0xff, 0xac, 0xc3, 0xce, 0x02, 0xfa, 0x89,
	0x09, 0x1b, 0x72, 0xe3, 0xd1, 0x15, 0x6a, 0xd2, 0x06, 0xcd, 0x4c, 0xf2, 0x0e, 0x6c, 0xfa, 0xe3,
	0x90, 0x71, 0x3c, 0xfa, 0xc1, 0x09, 0xc7, 0x4a, 0x2f, 0x92, 0xb7, 0x59, 0x27, 0x79, 0x0c, 0x77,
	0x3d, 0x0c, 0x50, 0xe0, 0x53, 0x1c, 0x31, 0x8e, 0x14, 0xa3, 0xc0, 0x71, 0x51, 0x29, 0xa5, 0x41,
	0xab, 0x42, 0xe4, 0x0b, 0xb0, 0x2a, 0xdc, 0x03, 0x1c, 0xf9, 0x21, 0x7a, 0x4a, 0x4f, 0x0d, 0xba,
	0x04, 0x41, 0x0e, 0x60, 0xc7, 0xf1, 0x3c, 0x5f, 0x2e, 0xdf, 0x09, 0xce, 0xd0, 0xe5, 0x28, 0x4e,
	0x13, 0x11, 0x25, 0x42, 0xaa, 0x4e, 0xae, 0x70, 0x51, 0x58, 0xf6, 0xea, 0x04, 0xbe, 0x13, 0x63,
	0x6c, 0xae, 0x2b, 0x64, 0x66, 0x92, 0x73, 0xe8, 0xb8, 0x49, 0x2c, 0xd8, 0xe4, 0xa5, 0x3f, 0x41,
	0x26, 0x4b, 0x6d, 0x28, 0xb6, 0x9f, 0xbc, 0x59, 0xc0, 0xbd, 0xa3, 0x99, 0x44, 0x5a, 0x2a, 0x64,
	0x7d, 0x0f, 0x9d, 0x59, 0x84, 0xd4, 0xa9, 0xcb, 0xd1, 0x11, 0xfa, 0x6c, 0x1a, 0x34, 0xb5, 0xa4,
	0x3f, 0x89, 0x3c, 0xe9, 0xaf, 0x69, 0xbf, 0xb6, 0xa4, 0x5f, 0xd3, 0xa1, 0x58, 0x35, 0x68, 0x6a,
	0xd9, 0xbf, 0x18, 0x60, 0x2e, 0x3a, 0x16, 0xff, 0xc1, 0xf1, 0xb7, 0xfb, 0xb0, 0xbb, 0x4c, 0x91,
	0x32, 0x27, 0xe1, 0x61, 0x6c, 0x1a, 0x8a, 0x7b, 0x35, 0xb6, 0x87, 0x70, 0x37, 0xcd, 0x39, 0x13,
	0x8e, 0x7b, 0x91, 0xdd, 0xe1, 0x9f, 0x40, 0x93, 0xa7, 0x9d, 0x68, 0x7c, 0xab, 0xff, 0x60, 0xc9,
	0x56, 0xd0, 0x6b, 0xb4, 0xfd, 0x1d, 0xdc, 0xc9, 0x1f, 0x84, 0x38, 0x62, 0x61, 0x2c, 0x15, 0xd7,
	0xf2, 0x7c, 0x67, 0x1c, 0xb2, 0x58, 0xf8, 0xae, 0xd6, 0x71, 0xab, 0xbf, 0x3b, 0x5f, 0x6f, 0x90,
	0x83, 0x68, 0x31, 0xc1, 0xfe, 0xad, 0x06, 0xdb, 0x73, 0x10, 0xf2, 0x10, 0x20, 0x62, 0x81, 0xef,
	0x4e, 0x5f, 0x48, 0x22, 0x34, 0xcf, 0x05, 0x0f, 0x79, 0x17, 0x3a, 0xda, 0x1a, 0x3a, 0xee, 0x85,
	0xc2, 0xd4, 0x14, 0xa6, 0xe4, 0x25, 0x1f, 0xc0, 0xf6, 0xb5, 0xe7, 0x15, 0xf2, 0xd8, 0x67, 0x19,
	0xd5, 0xf3, 0x01, 0xd2, 0x85, 0x96, 0x87, 0xb1, 0xcb, 0x7d, 0xa5, 0xbe, 0x94, 0xff, 0xa2, 0x4b,
	0xaa, 0x7c, 0x82, 0x71, 0xec, 0x8c, 0x51, 0xdd, 0xc2, 0x4d, 0x9a, 0x99, 0x4a, 0x13, 0xce, 0x38,
	0x13, 0xbf, 0x1a, 0x93, 0x13, 0xd8, 0xc2, 0x70, 0xc4, 0xb8, 0x8b, 0x13, 0x0c, 0xc5, 0x73, 0xbc,
	0xc2, 0x40, 0x69, 0xbf, 0x33, 0x43, 0xf8, 0x71, 0x09, 0x42, 0xe7, 0x92, 0x32, 0x8d, 0x34, 0x72,
	0x8d, 0xd8, 0x3f, 0x42, 0x3b, 0xdb, 0xa8, 0x67, 0xe1, 0x88, 0xe5, 0x9a, 0x31, 0x0a, 0x4f, 0x86,
	0x6c, 0xc7, 0x8f, 0xa3, 0xc0, 0x99, 0x16, 0x18, 0x2a, 0xba, 0xc8, 0x13, 0x68, 0x28, 0x16, 0xa4,
	0x64, 0xeb, 0x6a, 0xe7, 0xde, 0x2e, 0x2c, 0x6c, 0xa8, 0x08, 0x92, 0xe5, 0x69, 0x0e, 0xb3, 0xff,
	0xaa, 0x01, 0x5c, 0x07, 0x6e, 0x39, 0x6f, 0x89, 0xe8, 0xfa, 0x52, 0xa2, 0x57, 0x67, 0x89, 0xae,
	0x22, 0x75, 0xed, 0x36, 0xa4, 0x1e, 0xc0, 0xba, 0xcb, 0xc2, 0x91, 0x3f, 0x4e, 0x5f, 0xc4, 0x6e,
	0x65, 0xeb, 0xbd, 0x23, 0x85, 0x51, 0x2c, 0xa4, 0x78, 0xcb, 0x01, 0xb8, 0xf6, 0x96, 0x4e, 0xbe,
	0x71, 0xf3, 0x93, 0x6f, 0x41, 0x83, 0xe3, 0x65, 0xe2, 0x73, 0xf4, 0xd2, 0xfb, 0x3f, 0xb7, 0xed,
	0xdf, 0xeb, 0x60, 0xea, 0x39, 0x12, 0x8e, 0xd7, 0x47, 0x52, 0x9f, 0xe0, 0x73, 0x68, 0x6b, 0xf1,
	0x6a, 0x44, 0x7a, 0x88, 0x8b, 0x0f, 0xe9, 0xa2, 0xd4, 0xb4, 0x31, 0x1d, 0xd6, 0x0f, 0xe9, 0x4c,
	0x29, 0xeb, 0x0f, 0x03, 0xda, 0x45, 0x4c, 0x25, 0xdd, 0xc6, 0xed, 0xe8, 0xde, 0x29, 0xfb, 0xb2,
	0x77, 0xa9, 0xa6, 0xde, 0xa5, 0x45, 0xe1, 0x12, 0xc1, 0xf5, 0x1b, 0x13, 0x6c, 0x5d, 0xc2, 0xf6,
	0x5c, 0xbf, 0x15, 0x5f, 0x01, 0x5f, 0xcf, 0x7e, 0x05, 0x3c, 0xfe, 0xb7, 0x3c, 0x16, 0x3e, 0x07,
	0xde, 0xdf, 0x87, 0xad, 0x32, 0x17, 0xa4, 0x0d, 0x8d, 0xc3, 0xc1, 0xab, 0x67, 0x67, 0xa7, 0xf4,
	0x7c, 0x6b, 0x85, 0x6c, 0x42, 0xf3, 0xdb, 0xc3, 0x17, 0x83, 0xc3, 0x97, 0xd2, 0x34, 0xfa, 0x7f,
	0xd7, 0xa0, 0x91, 0x15, 0x27, 0x4f, 0x61, 0x23, 0x1d, 0x93, 0xfb, 0xf3, 0x57, 0x68, 0x3a, 0xb7,
	0x65, 0x55, 0x85, 0xf4, 0x75, 0x6c, 0xaf, 0x90, 0xe7, 0xf9, 0xcd, 0xa0, 0x6e, 0x7d, 0xf2, 0x70,
	0x1e, 0x5d, 0x7c, 0x0e, 0xde, 0x50, 0x6d, 0x00, 0x77, 0x4e, 0x50, 0xcc, 0x5c, 0x35, 0xf7, 0xe6,
	0xa8, 0x3f, 0x96, 0xbf, 0x14, 0xd6, 0x4e, 0xc5, 0x23, 0x22, 0x13, 0xec, 0x15, 0xf2, 0x15, 0x6c,
	0x9e, 0xa0, 0x18, 0xaa, 0xff, 0x92, 0xa5, 0x35, 0x66, 0xae, 0x9f, 0x1c, 0x6e, 0xaf, 0x90, 0x6f,
	0xa0, 0x99, 0xef, 0x05, 0x79, 0x74, 0x83, 0x1d, 0xb2, 0x16, 0x4c, 0x61, 0xaf, 0xbc, 0x5e, 0x57,
	0x9e, 0x0f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xdf, 0xcc, 0xdb, 0x44, 0x0d, 0x00, 0x00,
}
