// Copyright 2016-2022, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: pulumi/callback.proto

package pulumirpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallbackInvokeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference string           `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"` // the callback function reference to invoke.
	Args      *structpb.Struct `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`           // the arguments for the function invocation.
}

func (x *CallbackInvokeRequest) Reset() {
	*x = CallbackInvokeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pulumi_callback_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallbackInvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackInvokeRequest) ProtoMessage() {}

func (x *CallbackInvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulumi_callback_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackInvokeRequest.ProtoReflect.Descriptor instead.
func (*CallbackInvokeRequest) Descriptor() ([]byte, []int) {
	return file_pulumi_callback_proto_rawDescGZIP(), []int{0}
}

func (x *CallbackInvokeRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *CallbackInvokeRequest) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

type CallbackInvokeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Return   *structpb.Struct `protobuf:"bytes,1,opt,name=return,proto3" json:"return,omitempty"`     // the returned values, if invoke was successful.
	Failures []*CheckFailure  `protobuf:"bytes,2,rep,name=failures,proto3" json:"failures,omitempty"` // the failures if any arguments didn't pass verification.
}

func (x *CallbackInvokeResponse) Reset() {
	*x = CallbackInvokeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pulumi_callback_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallbackInvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackInvokeResponse) ProtoMessage() {}

func (x *CallbackInvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulumi_callback_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackInvokeResponse.ProtoReflect.Descriptor instead.
func (*CallbackInvokeResponse) Descriptor() ([]byte, []int) {
	return file_pulumi_callback_proto_rawDescGZIP(), []int{1}
}

func (x *CallbackInvokeResponse) GetReturn() *structpb.Struct {
	if x != nil {
		return x.Return
	}
	return nil
}

func (x *CallbackInvokeResponse) GetFailures() []*CheckFailure {
	if x != nil {
		return x.Failures
	}
	return nil
}

var File_pulumi_callback_proto protoreflect.FileDescriptor

var file_pulumi_callback_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x75, 0x6c, 0x75, 0x6d, 0x69, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x75, 0x6c, 0x75, 0x6d, 0x69, 0x72,
	0x70, 0x63, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x15, 0x70, 0x75, 0x6c, 0x75, 0x6d, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x15, 0x43, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x2b,
	0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x7e, 0x0a, 0x16, 0x43,
	0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x33, 0x0a, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x75, 0x6c, 0x75, 0x6d,
	0x69, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72,
	0x65, 0x52, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x73, 0x32, 0x5b, 0x0a, 0x08, 0x43,
	0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x4f, 0x0a, 0x06, 0x49, 0x6e, 0x76, 0x6f, 0x6b,
	0x65, 0x12, 0x20, 0x2e, 0x70, 0x75, 0x6c, 0x75, 0x6d, 0x69, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x75, 0x6c, 0x75, 0x6d, 0x69, 0x72, 0x70, 0x63, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x75, 0x6c, 0x75, 0x6d, 0x69, 0x2f, 0x70, 0x75,
	0x6c, 0x75, 0x6d, 0x69, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x3b, 0x70, 0x75, 0x6c, 0x75, 0x6d, 0x69, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pulumi_callback_proto_rawDescOnce sync.Once
	file_pulumi_callback_proto_rawDescData = file_pulumi_callback_proto_rawDesc
)

func file_pulumi_callback_proto_rawDescGZIP() []byte {
	file_pulumi_callback_proto_rawDescOnce.Do(func() {
		file_pulumi_callback_proto_rawDescData = protoimpl.X.CompressGZIP(file_pulumi_callback_proto_rawDescData)
	})
	return file_pulumi_callback_proto_rawDescData
}

var file_pulumi_callback_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pulumi_callback_proto_goTypes = []interface{}{
	(*CallbackInvokeRequest)(nil),  // 0: pulumirpc.CallbackInvokeRequest
	(*CallbackInvokeResponse)(nil), // 1: pulumirpc.CallbackInvokeResponse
	(*structpb.Struct)(nil),        // 2: google.protobuf.Struct
	(*CheckFailure)(nil),           // 3: pulumirpc.CheckFailure
}
var file_pulumi_callback_proto_depIdxs = []int32{
	2, // 0: pulumirpc.CallbackInvokeRequest.args:type_name -> google.protobuf.Struct
	2, // 1: pulumirpc.CallbackInvokeResponse.return:type_name -> google.protobuf.Struct
	3, // 2: pulumirpc.CallbackInvokeResponse.failures:type_name -> pulumirpc.CheckFailure
	0, // 3: pulumirpc.Callback.Invoke:input_type -> pulumirpc.CallbackInvokeRequest
	1, // 4: pulumirpc.Callback.Invoke:output_type -> pulumirpc.CallbackInvokeResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pulumi_callback_proto_init() }
func file_pulumi_callback_proto_init() {
	if File_pulumi_callback_proto != nil {
		return
	}
	file_pulumi_provider_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pulumi_callback_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallbackInvokeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pulumi_callback_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallbackInvokeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pulumi_callback_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pulumi_callback_proto_goTypes,
		DependencyIndexes: file_pulumi_callback_proto_depIdxs,
		MessageInfos:      file_pulumi_callback_proto_msgTypes,
	}.Build()
	File_pulumi_callback_proto = out.File
	file_pulumi_callback_proto_rawDesc = nil
	file_pulumi_callback_proto_goTypes = nil
	file_pulumi_callback_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CallbackClient is the client API for Callback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CallbackClient interface {
	Invoke(ctx context.Context, in *CallbackInvokeRequest, opts ...grpc.CallOption) (*CallbackInvokeResponse, error)
}

type callbackClient struct {
	cc grpc.ClientConnInterface
}

func NewCallbackClient(cc grpc.ClientConnInterface) CallbackClient {
	return &callbackClient{cc}
}

func (c *callbackClient) Invoke(ctx context.Context, in *CallbackInvokeRequest, opts ...grpc.CallOption) (*CallbackInvokeResponse, error) {
	out := new(CallbackInvokeResponse)
	err := c.cc.Invoke(ctx, "/pulumirpc.Callback/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallbackServer is the server API for Callback service.
type CallbackServer interface {
	Invoke(context.Context, *CallbackInvokeRequest) (*CallbackInvokeResponse, error)
}

// UnimplementedCallbackServer can be embedded to have forward compatible implementations.
type UnimplementedCallbackServer struct {
}

func (*UnimplementedCallbackServer) Invoke(context.Context, *CallbackInvokeRequest) (*CallbackInvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}

func RegisterCallbackServer(s *grpc.Server, srv CallbackServer) {
	s.RegisterService(&_Callback_serviceDesc, srv)
}

func _Callback_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallbackInvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallbackServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pulumirpc.Callback/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallbackServer).Invoke(ctx, req.(*CallbackInvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Callback_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pulumirpc.Callback",
	HandlerType: (*CallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _Callback_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pulumi/callback.proto",
}
