name: Downstream Codegen Tests
on:
  pull_request:
    paths:
    - 'pkg/codegen/**'
    - '!pkg/codegen/docs/**'
    - '.github/workflows/pr-test-codegen-downstream.yml'

permissions:
  contents: read

jobs:
    dispatch:
      runs-on: ubuntu-latest
      name: Test Downstream ${{ matrix.provider }} Codegen Tests
      steps:
        - name: Trigger upgrade
          uses: peter-evans/repository-dispatch@v2
          with:
            token: ${{ secrets.PULUMI_BOT_TOKEN }}
            repository: pulumi/pulumi-${{ matrix.provider }}
            event-type: upgrade-bridge
            client-payload: |-
              {
                 "target-pulumi-version": ${{ toJSON( github.sha ) }},
                 "target-bridge-version": "",
                 "pr-reviewers": ${{ toJSON( github.triggering_actor || 't0yv0' ) }},
                 "pr-description": "This is a downstream codegen test for ${{ github.run_id }} on pulumi/pulumi#${{ github.event.pull_request.number }}.",
                 "automerge": false
              }
      strategy:
        # GitHub recommends only issuing 1 API request per second, and never
        # concurrently.  For more information, see:
        # https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits
        max-parallel: 1
        matrix:
          provider: ["aws", "gcp", "azure", "azuread", "random", "kubernetes"]
        fail-fast: false
